### ISSUE TITLE
Is this project actively supported?

### ISSUE THREAD

**Issue by KevinMellott91** [zalando-incubator/spark-json-schema#38]
This project is very handy and I find it extremely useful (nice job!). However, it doesn't seem to have many recent commits or activity.

Can any of the committers weigh in on the level of support moving forward? I understand that this is a shared effort (hence, open-source), but is there an active roadmap or plan to keep this project active?

**Comment by hesserp** [comment]
Hi Kevin,
thank you for your interest in this project. Yes, the last activity here has happened some time ago. This project is currently not actively developed, so we have no roadmap. In the current state it totally fulfils the creators needs. Though we will give out guidance and might add new features upon request if it can be achieved with reasonable effort.

**Comment by KevinMellott91** [comment]
Sounds good - thanks for the info
