### ISSUE TITLE
Scala 2.12 support 

### ISSUE THREAD

**Issue by kraj007** [zalando-incubator/spark-json-schema#45]
Hello Team,

We are using spark 2.4.4 with scala 2.12.
Previously in our tech stack we used zalando package version 0.6.1 with scala 2.11.
Now while we upgrade , we would like to know if you guys are releasing scala 2.12 package.

We are eagerly waiting for this and if it takes time would like to know any alternatives specially in pyspark

**Comment by hesserp** [comment]
Hi, sorry for no reaction in a long time. Version 0.6.2 has been published using scala 2.12.
