### ISSUE TITLE
Load schema input as resourceStream

### ISSUE THREAD

**Issue by petz2000** [zalando-incubator/spark-json-schema#7]
In order to load a schema even when the resource is packaged in a jar, the inputFile loading is switched to use inputStream

**Comment by adamdec** [comment]
It might be somehow covered in my PR to scala_2.10 branch. I want to add possibility to read JSON schema from a String.

**Comment by hesserp** [comment]
yes, your method worked indeed. It's used to solve this problem in version 0.5

**Comment by adamdec** [comment]
Cool :)
